---
- include_role:
    name: docker

- name: Setting nginx config
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx.conf"
    owner: root
    group: root
    mode: '0644'

- name: Create nginx container
  community.docker.docker_container:
    name: "nginx"
    image: nginx:latest
    recreate: yes
    volumes:
      - /etc/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - name: web



